/* Настоящие логотипы марок — картинки, а не нарисованные знаки.

   Владелец попросил эмблемы «реальные, фото, а не нарисованные»:
   самодельные SVG-знаки (ладья, буквы в круге) читались иконками-заглушками.
   Файлы взяты из открытого набора filippofilip95/car-logos-dataset
   (уменьшенные версии 385×256, около 4 КБ) и лежат в public/brands/logos.

   Ключ — название марки в нижнем регистре без пробелов, дефисов и скобок:
   «Lada (ВАЗ)» → «lada», «Land Rover» → «landrover». Марок, которых в
   наборе нет (новые китайские, мото, катера, авиация), здесь тоже нет —
   для них остаётся прежний рисованный знак или надпись. */
const BRAND_LOGO_FILES: Record<string, string> = {
  "acura": "acura",
  "alfaromeo": "alfa-romeo",
  "astonmartin": "aston-martin",
  "audi": "audi",
  "bentley": "bentley",
  "bestune": "bestune",
  "bmw": "bmw",
  "bmwmotorrad": "bmw",
  "buick": "buick",
  "byd": "byd",
  "cadillac": "cadillac",
  "changan": "changan",
  "chery": "chery",
  "chevrolet": "chevrolet",
  "chrysler": "chrysler",
  "citroen": "citroen",
  "cupra": "cupra",
  "dacia": "dacia",
  "daewoo": "daewoo",
  "daf": "daf",
  "daihatsu": "daihatsu",
  "dodge": "dodge",
  "dongfeng": "dongfeng",
  "ds": "ds",
  "exeed": "exeed",
  "faw": "faw",
  "ferrari": "ferrari",
  "fiat": "fiat",
  "ford": "ford",
  "fordtrucks": "ford",
  "foton": "foton",
  "geely": "geely",
  "genesis": "genesis",
  "gmc": "gmc",
  "greatwall": "great-wall",
  "haval": "haval",
  "hino": "hino",
  "honda": "honda",
  "hondamarine": "honda",
  "hongqi": "hongqi",
  "hyundai": "hyundai",
  "hyundaice": "hyundai",
  "hyundaitrucks": "hyundai",
  "infiniti": "infiniti",
  "isuzu": "isuzu",
  "iveco": "iveco",
  "jac": "jac",
  "jaguar": "jaguar",
  "jeep": "jeep",
  "jetour": "jetour",
  "jetta": "jetta",
  "kamaz": "kamaz",
  "kgm": "ssangyong",
  "kgmssangyong": "ssangyong",
  "kia": "kia",
  "ktm": "ktm",
  "lada": "lada",
  "lamborghini": "lamborghini",
  "lancia": "lancia",
  "landrover": "land-rover",
  "leapmotor": "leapmotor",
  "lexus": "lexus",
  "liauto": "li-auto",
  "lincoln": "lincoln",
  "lixiang": "li-auto",
  "man": "man",
  "maserati": "maserati",
  "maybach": "maybach",
  "mazda": "mazda",
  "mclaren": "mclaren",
  "mercedes": "mercedes-benz",
  "mercedesbenz": "mercedes-benz",
  "mercedesbenztrucks": "mercedes-benz",
  "mercury": "mercury",
  "mini": "mini",
  "mitsubishi": "mitsubishi",
  "nio": "nio",
  "nissan": "nissan",
  "omoda": "omoda",
  "opel": "opel",
  "peugeot": "peugeot",
  "porsche": "porsche",
  "ram": "ram",
  "renault": "renault",
  "renaulttrucks": "renault",
  "roewe": "roewe",
  "rollsroyce": "rolls-royce",
  "scania": "scania",
  "seat": "seat",
  "shacman": "shacman",
  "skoda": "skoda",
  "smart": "smart",
  "ssangyong": "ssangyong",
  "subaru": "subaru",
  "suzuki": "suzuki",
  "suzukimarine": "suzuki",
  "tesla": "tesla",
  "toyota": "toyota",
  "triumph": "triumph",
  "volkswagen": "volkswagen",
  "volvo": "volvo",
  "volvoce": "volvo",
  "volvotrucks": "volvo",
  "vw": "volkswagen",
  "wey": "wey",
  "xpeng": "xpeng",
  "zeekr": "zeekr",
  "ваз": "lada",
  "газ": "gaz",
  "камаз": "kamaz",
  "маз": "maz",
  "уаз": "uaz",
}

export function brandLogoKey(brand: string): string {
  return brand.toLowerCase().replace(/\(.*?\)/g, "").replace(/[\s\-_/.]/g, "").trim()
}

/** Адрес картинки логотипа или null, если настоящего логотипа нет. */
export function brandLogoImage(brand: string): string | null {
  const file = BRAND_LOGO_FILES[brandLogoKey(brand)]
  return file ? `/brands/logos/${file}.png` : null
}
