/**
 * Полный каталог марок и моделей транспорта.
 * Источник: каталоги Auto.ru / Drom.ru / Kolesa.kz.
 * Флаги стран, популярность и модели актуальны на 2024-2026.
 */

export type CountryCode =
  | "RU"
  | "CN"
  | "JP"
  | "DE"
  | "KR"
  | "US"
  | "FR"
  | "GB"
  | "CZ"
  | "SE"
  | "IT"
  | "ES"
  | "AT"
  | "IN"
  | "OTHER"

export const COUNTRY_FLAGS: Record<CountryCode, string> = {
  RU: "🇷🇺",
  CN: "🇨🇳",
  JP: "🇯🇵",
  DE: "🇩🇪",
  KR: "🇰🇷",
  US: "🇺🇸",
  FR: "🇫🇷",
  GB: "🇬🇧",
  CZ: "🇨🇿",
  SE: "🇸🇪",
  IT: "🇮🇹",
  ES: "🇪🇸",
  AT: "🇦🇹",
  IN: "🇮🇳",
  OTHER: "🏳️",
}

export type BrandCategory = "cars" | "moto" | "trucks" | "special" | "water" | "air"

export interface Brand {
  name: string
  country: CountryCode
  popular: boolean
  models: string[]
  category: BrandCategory
}

/** Категории транспорта — вертикали */
export interface TransportCategory {
  slug: string
  label: string
  icon: string
  count?: number
}

export const TRANSPORT_CATEGORIES: TransportCategory[] = [
  { slug: "cars", label: "Легковые авто", icon: "Car" },
  { slug: "moto", label: "Мото", icon: "Motorbike" },
  { slug: "trucks", label: "Коммерческий транспорт", icon: "Truck" },
  { slug: "special", label: "Спецтехника", icon: "Tractor" },
  { slug: "water", label: "Водный транспорт", icon: "Speedboat" },
  { slug: "air", label: "Воздушный транспорт", icon: "Plane" },
  { slug: "parts", label: "Запчасти", icon: "Tools" },
  { slug: "services", label: "Услуги", icon: "Wrench" },
]

/** Все марки с флагами, популярностью и моделями */
export const ALL_BRANDS: Brand[] = [
  // ===================================================================
  // ЛЕГКОВЫЕ АВТО (cars)
  // ===================================================================

  // -------------------- РОССИЯ --------------------
  {
    name: "Lada (ВАЗ)",
    country: "RU",
    popular: true,
    category: "cars",
    models: [
      "Vesta",
      "Granta",
      "Niva Travel",
      "Niva Legend",
      "Largus",
      "XRAY",
      "Vesta SW",
      "Priora",
      "Kalina",
      "2114",
      "2110",
      "Vesta Cross",
    ],
  },
  {
    name: "УАЗ",
    country: "RU",
    popular: false,
    category: "cars",
    models: ["Patriot", "Hunter", "Pickup", "Профи", "Буханка", "3163"],
  },
  {
    name: "Москвич",
    country: "RU",
    popular: false,
    category: "cars",
    models: ["3", "6", "JAC JS6", "JAC J7"],
  },
  {
    name: "Aurus",
    country: "RU",
    popular: false,
    category: "cars",
    models: ["Senat", "Komnad"],
  },

  // -------------------- КИТАЙ --------------------
  {
    name: "Geely",
    country: "CN",
    popular: true,
    category: "cars",
    models: [
      "Coolray",
      "Atlas",
      "Tugella",
      "Monjaro",
      "Emgrand",
      "Geometry C",
      "Preface",
      "Okavango",
    ],
  },
  {
    name: "Chery",
    country: "CN",
    popular: true,
    category: "cars",
    models: [
      "Tiggo 4 Pro",
      "Tiggo 7 Pro",
      "Tiggo 8 Pro Max",
      "Arrizo 8",
      "Arrizo 5",
      "Exeed TXL",
    ],
  },
  {
    name: "Haval",
    country: "CN",
    popular: true,
    category: "cars",
    models: ["Jolion", "F7", "F7x", "Dargo", "H6", "H9", "M6", "初恋"],
  },
  {
    name: "Changan",
    country: "CN",
    popular: true,
    category: "cars",
    models: [
      "CS35 Plus",
      "CS55",
      "CS75 Plus",
      "UNI-K",
      "UNI-V",
      "UNI-T",
      "Eado",
      "Lamore",
      "Alsvin",
    ],
  },
  {
    name: "Exeed",
    country: "CN",
    popular: true,
    category: "cars",
    models: ["TXL", "VX", "LX", "RX", "Sterra ES"],
  },
  {
    name: "Omoda",
    country: "CN",
    popular: true,
    category: "cars",
    models: ["C5", "S5", "C7", "E5"],
  },
  {
    name: "Jetour",
    country: "CN",
    popular: true,
    category: "cars",
    models: ["Dashing", "X70 Plus", "X90 Plus", "Traveller", "Dasheng"],
  },
  {
    name: "Tank",
    country: "CN",
    popular: true,
    category: "cars",
    models: ["300", "500", "700"],
  },
  {
    name: "BYD",
    country: "CN",
    popular: true,
    category: "cars",
    models: ["Han", "Tang", "Seal", "Atto 3", "Dolphin", "Yuan Plus", "Song"],
  },
  {
    name: "Hongqi",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["H9", "E-HS9", "HS5", "H5"],
  },
  {
    name: "Li Auto",
    country: "CN",
    popular: true,
    category: "cars",
    models: ["L7", "L8", "L9", "Mega", "L6"],
  },
  {
    name: "Zeekr",
    country: "CN",
    popular: true,
    category: "cars",
    models: ["001", "X", "007", "009"],
  },
  {
    name: "Voyah",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["Free", "Dream", "Passion"],
  },
  {
    name: "Leapmotor",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["C11", "T03", "C01", "C10"],
  },
  {
    name: "GAC",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["GS3", "GS8", "M8", "GS4"],
  },
  {
    name: "JAC",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["J7", "S3", "T8", "Refine"],
  },
  {
    name: "Great Wall",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["Wingle 7", "Poer", "Cannon"],
  },
  {
    name: "Jetta",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["VA3", "VS5", "VS7"],
  },
  {
    name: "Nio",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["ET7", "ET5", "ES6", "ES8", "EC6"],
  },
  {
    name: "Xpeng",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["G9", "P7", "G6", "P5"],
  },
  {
    name: "Avatr",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["11", "12"],
  },
  {
    name: "Aito",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["M5", "M7", "M9"],
  },
  {
    name: "Denza",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["D9", "N7"],
  },
  {
    name: "Ora",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["Good Cat", "Black Cat"],
  },
  {
    name: "Wey",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["Coffee 01", "Macchiato"],
  },
  {
    name: "Roewe",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["RX5", "i5"],
  },
  {
    name: "Skyworth",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["EV6"],
  },
  {
    name: "Bestune",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["T99", "T77"],
  },
  {
    name: "Forthing",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["T5 EVO", "Yacht"],
  },
  {
    name: "Kaiyi",
    country: "CN",
    popular: false,
    category: "cars",
    models: ["Xuanjie", "Xuandu"],
  },

  // -------------------- ЯПОНИЯ --------------------
  {
    name: "Toyota",
    country: "JP",
    popular: true,
    category: "cars",
    models: [
      "Camry",
      "RAV4",
      "Land Cruiser 200",
      "Land Cruiser 300",
      "Land Cruiser Prado 150",
      "Highlander",
      "Corolla",
      "Hilux",
      "C-HR",
      "Alphard",
      "Yaris",
      "Prius",
      "Crown",
      "Fortuner",
      "Mark II",
    ],
  },
  {
    name: "Lexus",
    country: "JP",
    popular: true,
    category: "cars",
    models: [
      "RX 350",
      "RX 300",
      "RX 450h",
      "LX 600",
      "LX 570",
      "NX 300",
      "NX 200",
      "ES 350",
      "GX 460",
      "GX 550",
      "IS 250",
      "IS 300",
      "LS 460",
      "LC 500",
      "LM",
      "UX 250",
    ],
  },
  {
    name: "Nissan",
    country: "JP",
    popular: true,
    category: "cars",
    models: [
      "Qashqai",
      "X-Trail",
      "Murano",
      "Patrol",
      "Almera",
      "Terrano",
      "Juke",
      "Teana",
      "Pathfinder",
      "Navara",
      "GT-R",
      "Sunny",
    ],
  },
  {
    name: "Honda",
    country: "JP",
    popular: true,
    category: "cars",
    models: ["CR-V", "Pilot", "Civic", "Accord", "HR-V", "Stepwgn", "Odyssey", "BR-V"],
  },
  {
    name: "Mazda",
    country: "JP",
    popular: true,
    category: "cars",
    models: [
      "CX-5",
      "CX-7",
      "CX-9",
      "CX-30",
      "CX-50",
      "Mazda 3",
      "Mazda 6",
      "CX-60",
    ],
  },
  {
    name: "Mitsubishi",
    country: "JP",
    popular: true,
    category: "cars",
    models: [
      "Outlander",
      "Pajero Sport",
      "ASX",
      "L200",
      "Eclipse Cross",
      "Lancer",
      "Pajero",
      "Montero",
    ],
  },
  {
    name: "Subaru",
    country: "JP",
    popular: false,
    category: "cars",
    models: ["Forester", "Outback", "XV", "Legacy", "Levorg", "WRX", "BRZ"],
  },
  {
    name: "Suzuki",
    country: "JP",
    popular: false,
    category: "cars",
    models: ["Jimny", "Vitara", "SX4", "Swift", "Grand Vitara"],
  },
  {
    name: "Daihatsu",
    country: "JP",
    popular: false,
    category: "cars",
    models: ["Terios", "Materia", "Sirion"],
  },
  {
    name: "Infiniti",
    country: "JP",
    popular: false,
    category: "cars",
    models: ["QX50", "QX60", "QX80", "Q50", "Q70", "QX30"],
  },
  {
    name: "Acura",
    country: "JP",
    popular: false,
    category: "cars",
    models: ["RDX", "MDX", "TLX"],
  },

  // -------------------- ГЕРМАНИЯ --------------------
  {
    name: "BMW",
    country: "DE",
    popular: true,
    category: "cars",
    models: [
      "X5",
      "X3",
      "X7",
      "X6",
      "X1",
      "X4",
      "X2",
      "5 серии",
      "3 серии",
      "7 серии",
      "M5",
      "M3",
      "M4",
      "X5 M",
      "4 серии",
      "2 серии",
    ],
  },
  {
    name: "Mercedes-Benz",
    country: "DE",
    popular: true,
    category: "cars",
    models: [
      "GLE 350d",
      "GLE 400",
      "GLS",
      "S-класс",
      "E-класс",
      "C-класс",
      "G-класс",
      "GLC",
      "GLA",
      "Maybach S",
      "V-класс",
      "A-класс",
      "CLA",
      "CLS",
      "EQS",
      "AMG GT",
    ],
  },
  {
    name: "Audi",
    country: "DE",
    popular: true,
    category: "cars",
    models: [
      "Q7",
      "Q5",
      "Q3",
      "Q8",
      "A6",
      "A4",
      "A8",
      "e-tron",
      "RS6",
      "TT",
      "A5",
      "Q2",
      "A3",
    ],
  },
  {
    name: "Volkswagen",
    country: "DE",
    popular: true,
    category: "cars",
    models: [
      "Tiguan",
      "Touareg",
      "Polo",
      "Golf",
      "Passat",
      "T-Roc",
      "Arteon",
      "Teramont",
      "Caddy",
      "Transporter",
      "Amarok",
      "Taos",
      "T-Cross",
    ],
  },
  {
    name: "Porsche",
    country: "DE",
    popular: true,
    category: "cars",
    models: ["Cayenne", "Macan", "911", "Panamera", "Taycan", "Cayman", "Boxster", "718"],
  },
  {
    name: "Opel",
    country: "DE",
    popular: false,
    category: "cars",
    models: ["Astra", "Mokka", "Grandland", "Corsa", "Insignia", "Vivaro", "Zafira"],
  },
  {
    name: "Maybach",
    country: "DE",
    popular: false,
    category: "cars",
    models: ["S 580", "GLS 600", "S 680"],
  },
  {
    name: "Smart",
    country: "DE",
    popular: false,
    category: "cars",
    models: ["ForTwo", "ForFour", "#1", "#3"],
  },

  // -------------------- КОРЕЯ --------------------
  {
    name: "Kia",
    country: "KR",
    popular: true,
    category: "cars",
    models: [
      "Rio",
      "Sportage",
      "Sorento",
      "K5",
      "Seltos",
      "Cerato",
      "Mohave",
      "Carnival",
      "Stinger",
      "Picanto",
      "Ceed",
      "K900",
    ],
  },
  {
    name: "Hyundai",
    country: "KR",
    popular: true,
    category: "cars",
    models: [
      "Solaris",
      "Creta",
      "Tucson",
      "Santa Fe",
      "Sonata",
      "Elantra",
      "Palisade",
      "Staria",
      "Accent",
      "i30",
      "Bayon",
    ],
  },
  {
    name: "Genesis",
    country: "KR",
    popular: false,
    category: "cars",
    models: ["G80", "G90", "GV80", "GV70", "GV60", "G70"],
  },
  {
    name: "SsangYong",
    country: "KR",
    popular: false,
    category: "cars",
    models: ["Actyon", "Rexton", "Tivoli", "Kyron", "Korando"],
  },
  {
    name: "Daewoo",
    country: "KR",
    popular: false,
    category: "cars",
    models: ["Matiz", "Nexia", "Gentra", "Lacetti"],
  },

  // -------------------- США --------------------
  {
    name: "Ford",
    country: "US",
    popular: true,
    category: "cars",
    models: [
      "Focus",
      "Mondeo",
      "Kuga",
      "Explorer",
      "EcoSport",
      "F-150",
      "Mustang",
      "Edge",
      "Fiesta",
      "Transit",
    ],
  },
  {
    name: "Chevrolet",
    country: "US",
    popular: true,
    category: "cars",
    models: [
      "Cobalt",
      "Lacetti",
      "Captiva",
      "Cruze",
      "Aveo",
      "Niva",
      "Tahoe",
      "Camaro",
      "Malibu",
      "Traverse",
    ],
  },
  {
    name: "Cadillac",
    country: "US",
    popular: false,
    category: "cars",
    models: ["XT5", "Escalade", "CT6", "XT4", "CT5"],
  },
  {
    name: "Tesla",
    country: "US",
    popular: true,
    category: "cars",
    models: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
  },
  {
    name: "Jeep",
    country: "US",
    popular: false,
    category: "cars",
    models: ["Wrangler", "Cherokee", "Grand Cherokee", "Compass", "Renegade", "Gladiator"],
  },
  {
    name: "Dodge",
    country: "US",
    popular: false,
    category: "cars",
    models: ["Charger", "Durango", "Challenger", "Ram"],
  },
  {
    name: "Chrysler",
    country: "US",
    popular: false,
    category: "cars",
    models: ["300C", "Pacifica", "Voyager"],
  },
  {
    name: "Lincoln",
    country: "US",
    popular: false,
    category: "cars",
    models: ["Navigator", "Aviator", "Nautilus"],
  },
  {
    name: "Buick",
    country: "US",
    popular: false,
    category: "cars",
    models: ["Enclave", "Encore", "LaCrosse"],
  },
  {
    name: "GMC",
    country: "US",
    popular: false,
    category: "cars",
    models: ["Yukon", "Sierra", "Terrain"],
  },
  {
    name: "Ram",
    country: "US",
    popular: false,
    category: "cars",
    models: ["1500", "2500"],
  },

  // -------------------- ЧЕХИЯ --------------------
  {
    name: "Skoda",
    country: "CZ",
    popular: true,
    category: "cars",
    models: ["Octavia", "Kodiaq", "Rapid", "Superb", "Karoq", "Fabia", "Kamiq", "Scala", "Enyaq"],
  },

  // -------------------- ШВЕЦИЯ --------------------
  {
    name: "Volvo",
    country: "SE",
    popular: false,
    category: "cars",
    models: ["XC90", "XC60", "XC40", "S90", "V60", "V90", "EX30", "EX90", "S60", "V40"],
  },

  // -------------------- ВЕЛИКОБРИТАНИЯ --------------------
  {
    name: "Land Rover",
    country: "GB",
    popular: true,
    category: "cars",
    models: ["Range Rover", "Range Rover Sport", "Discovery", "Defender", "Evoque", "Velar"],
  },
  {
    name: "Jaguar",
    country: "GB",
    popular: false,
    category: "cars",
    models: ["XF", "F-Pace", "E-Pace", "I-Pace", "XE", "F-Type"],
  },
  {
    name: "Mini",
    country: "GB",
    popular: false,
    category: "cars",
    models: ["Cooper", "Countryman", "Clubman", "Paceman"],
  },
  {
    name: "Bentley",
    country: "GB",
    popular: false,
    category: "cars",
    models: ["Bentayga", "Continental GT", "Flying Spur", "Mulsanne"],
  },
  {
    name: "Rolls-Royce",
    country: "GB",
    popular: false,
    category: "cars",
    models: ["Phantom", "Cullinan", "Ghost", "Wraith", "Spectre"],
  },
  {
    name: "Aston Martin",
    country: "GB",
    popular: false,
    category: "cars",
    models: ["DBX", "Vantage", "DB11", "DB12"],
  },
  {
    name: "McLaren",
    country: "GB",
    popular: false,
    category: "cars",
    models: ["720S", "GT", "Artura"],
  },

  // -------------------- ФРАНЦИЯ --------------------
  {
    name: "Renault",
    country: "FR",
    popular: true,
    category: "cars",
    models: [
      "Logan",
      "Duster",
      "Sandero",
      "Kaptur",
      "Arkana",
      "Megane",
      "Koleos",
      "Taliant",
      "Kangoo",
      "Latitude",
    ],
  },
  {
    name: "Peugeot",
    country: "FR",
    popular: false,
    category: "cars",
    models: ["308", "3008", "5008", "208", "Partner", "Traveller", "408", "508"],
  },
  {
    name: "Citroen",
    country: "FR",
    popular: false,
    category: "cars",
    models: ["C4", "C5 Aircross", "Berlingo", "C3", "C3 Aircross"],
  },
  {
    name: "DS",
    country: "FR",
    popular: false,
    category: "cars",
    models: ["DS 7", "DS 4", "DS 3", "DS 9"],
  },

  // -------------------- ИТАЛИЯ --------------------
  {
    name: "Fiat",
    country: "IT",
    popular: false,
    category: "cars",
    models: ["Doblo", "500", "Punto", "Tipo", "Panda", "Ducato", "Fullback"],
  },
  {
    name: "Alfa Romeo",
    country: "IT",
    popular: false,
    category: "cars",
    models: ["Giulia", "Stelvio", "Tonale", "Giulietta"],
  },
  {
    name: "Ferrari",
    country: "IT",
    popular: false,
    category: "cars",
    models: ["Roma", "296 GTB", "SF90", "812", "Purosangue"],
  },
  {
    name: "Lamborghini",
    country: "IT",
    popular: false,
    category: "cars",
    models: ["Urus", "Huracan", "Revuelto", "Aventador"],
  },
  {
    name: "Maserati",
    country: "IT",
    popular: false,
    category: "cars",
    models: ["Levante", "Ghibli", "Grecale", "Quattroporte", "MC20"],
  },
  {
    name: "Lancia",
    country: "IT",
    popular: false,
    category: "cars",
    models: ["Ypsilon", "Delta"],
  },

  // -------------------- ИСПАНИЯ --------------------
  {
    name: "Seat",
    country: "ES",
    popular: false,
    category: "cars",
    models: ["Leon", "Ateca", "Ibiza", "Tarraco", "Arona"],
  },
  {
    name: "Cupra",
    country: "ES",
    popular: false,
    category: "cars",
    models: ["Formentor", "Leon", "Born", "Ateca"],
  },

  // -------------------- ПРОЧЕЕ --------------------
  {
    name: "Dacia",
    country: "OTHER",
    popular: false,
    category: "cars",
    models: ["Logan", "Sandero", "Duster", "Jogger", "Spring"],
  },

  // ===================================================================
  // МОТО (moto)
  // ===================================================================
  {
    name: "Honda",
    country: "JP",
    popular: true,
    category: "moto",
    models: ["CBR 650", "Africa Twin", "Gold Wing", "PCX", "Monkey"],
  },
  {
    name: "Yamaha",
    country: "JP",
    popular: true,
    category: "moto",
    models: ["YZF-R1", "MT-07", "Ténéré 700", "XMAX", "FZ6"],
  },
  {
    name: "Kawasaki",
    country: "JP",
    popular: true,
    category: "moto",
    models: ["Ninja 400", "Z900", "Versys 650", "KLR650", "Vulcan S"],
  },
  {
    name: "Suzuki",
    country: "JP",
    popular: true,
    category: "moto",
    models: ["GSX-R1000", "V-Strom 650", "Burgman 400", "Hayabusa", "DR-Z400"],
  },
  {
    name: "BMW Motorrad",
    country: "DE",
    popular: true,
    category: "moto",
    models: ["R 1250 GS", "F 800 GS", "S 1000 RR", "G 310 GS", "K 1600 GTL"],
  },
  {
    name: "Harley-Davidson",
    country: "US",
    popular: true,
    category: "moto",
    models: ["Sportster", "Softail", "Road Glide", "Pan America", "LiveWire"],
  },
  {
    name: "Ducati",
    country: "IT",
    popular: true,
    category: "moto",
    models: ["Panigale V4", "Monster", "Multistrada", "Scrambler", "Hypermotard"],
  },
  {
    name: "KTM",
    country: "AT",
    popular: true,
    category: "moto",
    models: ["390 Duke", "790 Adventure", "1290 Super Duke", "RC 390", "500 EXC-F"],
  },
  {
    name: "Triumph",
    country: "GB",
    popular: false,
    category: "moto",
    models: ["Bonneville", "Tiger 900", "Street Triple", "Rocket 3", "Scrambler 1200"],
  },
  {
    name: "Royal Enfield",
    country: "IN",
    popular: false,
    category: "moto",
    models: ["Classic 350", "Himalayan", "Meteor 350", "Interceptor 650", "Hunter 350"],
  },
  {
    name: "Aprilia",
    country: "IT",
    popular: false,
    category: "moto",
    models: ["RS 660", "Tuono 660", "Tuareg 660", "RSV4", "Dorsoduro"],
  },
  {
    name: "MV Agusta",
    country: "IT",
    popular: false,
    category: "moto",
    models: ["Brutale 800", "Dragster", "F3", "Superveloce", "Rush"],
  },
  {
    name: "ИЖ",
    country: "RU",
    popular: false,
    category: "moto",
    models: ["Планета", "Юпитер", "Корнет"],
  },
  {
    name: "Урал",
    country: "RU",
    popular: false,
    category: "moto",
    models: ["M70", "Gear-Up", "Patrol", "Sahara"],
  },
  {
    name: "Bajaj",
    country: "IN",
    popular: false,
    category: "moto",
    models: ["Pulsar 150", "Boxer", "Dominar 400", "Pulsar NS200", "Avenger"],
  },
  {
    name: "Irbis",
    country: "OTHER",
    popular: false,
    category: "moto",
    models: ["TTR 250", "WR 250", "ATR 250"],
  },
  {
    name: "Motoland",
    country: "OTHER",
    popular: false,
    category: "moto",
    models: ["XT 250 ST", "Skyracer GT 250", "Cross 250"],
  },

  // ===================================================================
  // ГРУЗОВИКИ (trucks)
  // ===================================================================
  {
    name: "КамАЗ",
    country: "RU",
    popular: true,
    category: "trucks",
    models: ["6520", "65115", "5490", "43118", "4308", "65201"],
  },
  {
    name: "МАЗ",
    country: "RU",
    popular: true,
    category: "trucks",
    models: ["6430", "5440", "6312", "5516", "4370"],
  },
  {
    name: "ГАЗ",
    country: "RU",
    popular: true,
    category: "trucks",
    models: ["Валдай", "Газель NEXT", "Соболь"],
  },
  {
    name: "ЗИЛ",
    country: "RU",
    popular: false,
    category: "trucks",
    models: ["130", "4331", "5301 Бычок"],
  },
  {
    name: "Volvo Trucks",
    country: "SE",
    popular: true,
    category: "trucks",
    models: ["FH16", "FMX", "FH", "FE", "FL"],
  },
  {
    name: "Scania",
    country: "SE",
    popular: true,
    category: "trucks",
    models: ["R500", "S730", "G440", "P360"],
  },
  {
    name: "MAN",
    country: "DE",
    popular: true,
    category: "trucks",
    models: ["TGX", "TGS", "TGM", "TGL"],
  },
  {
    name: "Mercedes-Benz Trucks",
    country: "DE",
    popular: true,
    category: "trucks",
    models: ["Actros", "Arocs", "Atego", "Econic"],
  },
  {
    name: "DAF",
    country: "OTHER",
    popular: false,
    category: "trucks",
    models: ["XF", "XG", "CF", "LF"],
  },
  {
    name: "Renault Trucks",
    country: "FR",
    popular: false,
    category: "trucks",
    models: ["T High", "K", "T", "T Low"],
  },
  {
    name: "Iveco",
    country: "IT",
    popular: false,
    category: "trucks",
    models: ["S-Way", "X-Way", "Stralis", "Daily"],
  },
  {
    name: "Ford Trucks",
    country: "US",
    popular: false,
    category: "trucks",
    models: ["F-MAX", "Cargo"],
  },
  {
    name: "Hyundai Trucks",
    country: "KR",
    popular: false,
    category: "trucks",
    models: ["HD78", "HD120", "HD170"],
  },
  {
    name: "Isuzu",
    country: "JP",
    popular: false,
    category: "trucks",
    models: ["NQR", "NPR", "CYZ", "ELF"],
  },
  {
    name: "Hino",
    country: "JP",
    popular: false,
    category: "trucks",
    models: ["500", "300", "700"],
  },
  {
    name: "Dongfeng",
    country: "CN",
    popular: false,
    category: "trucks",
    models: ["DFL1160", "DFL1250", "KR"],
  },
  {
    name: "Shacman",
    country: "CN",
    popular: false,
    category: "trucks",
    models: ["X3000", "F3000", "X6000"],
  },
  {
    name: "Howo",
    country: "CN",
    popular: false,
    category: "trucks",
    models: ["7", "TX", "ZZ"],
  },
  {
    name: "FAW",
    country: "CN",
    popular: false,
    category: "trucks",
    models: ["CA3310", "CA3250"],
  },
  {
    name: "Foton",
    country: "CN",
    popular: false,
    category: "trucks",
    models: ["Auman", "Aumark", "View"],
  },

  // ===================================================================
  // СПЕЦТЕХНИКА (special)
  // ===================================================================
  {
    name: "Caterpillar",
    country: "US",
    popular: true,
    category: "special",
    models: ["320", "D6", "980M", "336", "14M"],
  },
  {
    name: "Komatsu",
    country: "JP",
    popular: true,
    category: "special",
    models: ["PC200", "D85", "WA380", "PC300"],
  },
  {
    name: "Hitachi",
    country: "JP",
    popular: true,
    category: "special",
    models: ["ZX350", "ZX200", "ZW220"],
  },
  {
    name: "JCB",
    country: "GB",
    popular: true,
    category: "special",
    models: ["3CX", "4CX", "3D", "JS220", "8014"],
  },
  {
    name: "Volvo CE",
    country: "SE",
    popular: true,
    category: "special",
    models: ["EC220", "L120H", "A40G"],
  },
  {
    name: "XCMG",
    country: "CN",
    popular: true,
    category: "special",
    models: ["XE215", "LW300", "GR215"],
  },
  {
    name: "Sany",
    country: "CN",
    popular: false,
    category: "special",
    models: ["SY215", "SY365", "SAC1300"],
  },
  {
    name: "Liebherr",
    country: "DE",
    popular: false,
    category: "special",
    models: ["R 926", "L 586", "PR 736"],
  },
  {
    name: "Doosan",
    country: "KR",
    popular: false,
    category: "special",
    models: ["DX225", "DL550"],
  },
  {
    name: "Hyundai CE",
    country: "KR",
    popular: false,
    category: "special",
    models: ["R210", "HL760"],
  },
  {
    name: "Kobelco",
    country: "JP",
    popular: false,
    category: "special",
    models: ["SK210", "SK350"],
  },
  {
    name: "Bobcat",
    country: "US",
    popular: false,
    category: "special",
    models: ["S570", "T650", "E35"],
  },
  {
    name: "Case",
    country: "US",
    popular: false,
    category: "special",
    models: ["580N", "CX210", "621F"],
  },
  {
    name: "New Holland",
    country: "OTHER",
    popular: false,
    category: "special",
    models: ["E215B", "C238", "W190B"],
  },
  {
    name: "John Deere",
    country: "US",
    popular: false,
    category: "special",
    models: ["200G LC", "644L", "700K"],
  },
  {
    name: "Амкодор",
    country: "RU",
    popular: false,
    category: "special",
    models: ["342B", "333", "320"],
  },
  {
    name: "МТЗ",
    country: "RU",
    popular: true,
    category: "special",
    models: ["Беларус 82.1", "1221", "952", "1025"],
  },
  {
    name: "Терекс",
    country: "RU",
    popular: false,
    category: "special",
    models: ["ДТ-20", "ТЛ-2А"],
  },

  // ===================================================================
  // ВОДНЫЙ ТРАНСПОРТ (water)
  // ===================================================================
  {
    name: "Yamaha Marine",
    country: "JP",
    popular: true,
    category: "water",
    models: ["F200", "F300", "F150"],
  },
  {
    name: "Suzuki Marine",
    country: "JP",
    popular: false,
    category: "water",
    models: ["DF250", "DF150", "DF350"],
  },
  {
    name: "Mercury",
    country: "US",
    popular: true,
    category: "water",
    models: ["Verado 300", "Pro XS 250", "FourStroke 150"],
  },
  {
    name: "Honda Marine",
    country: "JP",
    popular: false,
    category: "water",
    models: ["BF250", "BF150", "BF100"],
  },
  {
    name: "Sea-Doo",
    country: "OTHER",
    popular: true,
    category: "water",
    models: ["GTX 300", "Spark", "RXT-X 300", "Wake Pro 230"],
  },
  {
    name: "Kawasaki Jet Ski",
    country: "JP",
    popular: false,
    category: "water",
    models: ["Ultra 310", "STX-15F", "SX-R"],
  },
  {
    name: "Bayliner",
    country: "US",
    popular: true,
    category: "water",
    models: ["VR5", "Element E18", "M17"],
  },
  {
    name: "Bennington",
    country: "US",
    popular: false,
    category: "water",
    models: ["S Series", "R Series", "Q Series"],
  },
  {
    name: "MasterCraft",
    country: "US",
    popular: false,
    category: "water",
    models: ["XT20", "X24", "XT23"],
  },
  {
    name: "Malibu",
    country: "US",
    popular: false,
    category: "water",
    models: ["Wakesetter 23 LSV", "Response TXi"],
  },
  {
    name: "Correct Craft",
    country: "US",
    popular: false,
    category: "water",
    models: ["Super Air Nautique G23", "GS22"],
  },
  {
    name: "Chaparral",
    country: "US",
    popular: false,
    category: "water",
    models: ["21 SSI", "25 SSI", "30 SSI"],
  },
  {
    name: "Four Winns",
    country: "US",
    popular: false,
    category: "water",
    models: ["H180", "H210", "H240"],
  },
  {
    name: "Glastron",
    country: "US",
    popular: false,
    category: "water",
    models: ["GT 180", "GT 205"],
  },
  {
    name: "Lund",
    country: "US",
    popular: false,
    category: "water",
    models: ["1675 Impact", "1875 Crossover"],
  },
  {
    name: "Tracker",
    country: "US",
    popular: false,
    category: "water",
    models: ["Pro Team 175", "Pro Team 195"],
  },
  {
    name: "Regal",
    country: "US",
    popular: false,
    category: "water",
    models: ["1900 ES", "2100 RX"],
  },
  {
    name: "Quicksilver",
    country: "OTHER",
    popular: false,
    category: "water",
    models: ["Activ 555", "Activ 675", "Activ 755"],
  },
  {
    name: "Jeanneau",
    country: "FR",
    popular: false,
    category: "water",
    models: ["Leader 10", "NC 9", "Sun Odyssey 410"],
  },
  {
    name: "Azimut",
    country: "IT",
    popular: true,
    category: "water",
    models: ["42", "55", "68", "95"],
  },
  {
    name: "Ferretti",
    country: "IT",
    popular: false,
    category: "water",
    models: ["550", "850", "960"],
  },

  // ===================================================================
  // ВОЗДУШНЫЙ ТРАНСПОРТ (air) — вертолёты и самолёты
  // ===================================================================
  {
    name: "Robinson Helicopter",
    country: "US",
    popular: true,
    category: "air",
    models: ["R44 Raven II", "R66", "R22"],
  },
  {
    name: "Airbus Helicopters",
    country: "OTHER",
    popular: true,
    category: "air",
    models: ["H125", "H130", "H145", "H160", "H225"],
  },
  {
    name: "Bell Helicopter",
    country: "US",
    popular: true,
    category: "air",
    models: ["505", "407", "429", "412", "525"],
  },
  {
    name: "McDonnell Douglas",
    country: "US",
    popular: false,
    category: "air",
    models: ["MD 500E", "MD 600N", "MD Explorer"],
  },
  {
    name: "AgustaWestland",
    country: "IT",
    popular: false,
    category: "air",
    models: ["AW109", "AW139", "AW169", "AW189"],
  },
  {
    name: "Eurocopter",
    country: "OTHER",
    popular: false,
    category: "air",
    models: ["EC120", "EC130", "EC135", "AS350 Écureuil"],
  },
  {
    name: "Kamov",
    country: "RU",
    popular: false,
    category: "air",
    models: ["Ka-32", "Ka-226", "Ka-52"],
  },
  {
    name: "Mil",
    country: "RU",
    popular: true,
    category: "air",
    models: ["Mi-8", "Mi-17", "Mi-26", "Mi-2"],
  },
  {
    name: "Cessna",
    country: "US",
    popular: true,
    category: "air",
    models: ["172 Skyhawk", "182 Skylane", "208 Caravan", "Citation M2"],
  },
  {
    name: "Piper",
    country: "US",
    popular: false,
    category: "air",
    models: ["Cherokee", "Arrow", "Seneca", "Matrix"],
  },
  {
    name: "Cirrus",
    country: "US",
    popular: false,
    category: "air",
    models: ["SR20", "SR22", "Vision Jet", "SF50"],
  },
  {
    name: "Beechcraft",
    country: "US",
    popular: false,
    category: "air",
    models: ["Bonanza", "Baron", "King Air 350", "Premier IA"],
  },
  {
    name: "Embraer",
    country: "OTHER",
    popular: false,
    category: "air",
    models: ["Phenom 100", "Phenom 300", "Legacy 450"],
  },
  {
    name: "Bombardier",
    country: "OTHER",
    popular: false,
    category: "air",
    models: ["Learjet 75", "Challenger 350", "Global 6000"],
  },
  {
    name: "Gulfstream",
    country: "US",
    popular: false,
    category: "air",
    models: ["G280", "G650", "G700"],
  },
  {
    name: "Dassault",
    country: "FR",
    popular: false,
    category: "air",
    models: ["Falcon 2000", "Falcon 900", "Falcon 7X"],
  },
  {
    name: "Aero",
    country: "CZ",
    popular: false,
    category: "air",
    models: ["L-39 Albatros", "L-29 Delfin"],
  },
  {
    name: "Як",
    country: "RU",
    popular: false,
    category: "air",
    models: ["Як-18Т", "Як-52", "Як-54"],
  },
  {
    name: "Сухой",
    country: "RU",
    popular: false,
    category: "air",
    models: ["Су-26", "Су-29", "Су-31"],
  },
  {
    name: "Tecnam",
    country: "IT",
    popular: false,
    category: "air",
    models: ["P2010", "P92", "P2008"],
  },
  {
    name: "Diamond",
    country: "AT",
    popular: false,
    category: "air",
    models: ["DA40", "DA42", "DA62", "D-JET"],
  },
]

/** Все бренды, отсортированные по имени (алиас) */
export const BRANDS: Brand[] = ALL_BRANDS

/** Только популярные бренды (для сайдбара / быстрого доступа) */
const _rawPopular: Brand[] = ALL_BRANDS.filter((b) => b.popular)

/** Имена брендов для Select, отсортированные по алфавиту */
export const BRAND_NAMES: string[] = Array.from(new Set(ALL_BRANDS.map((b) => b.name))).sort((a, b) =>
  a.localeCompare(b, "ru"),
)

/** Бренды конкретной категории транспорта */
export function getBrandsByCategory(category: BrandCategory): Brand[] {
  return ALL_BRANDS.filter((b) => b.category === category)
}

/** Получить модели бренда по названию (без учёта регистра) */
export function getModels(brandName: string, category?: BrandCategory): string[] {
  const brand = ALL_BRANDS.find(
    (b) => b.name.toLowerCase() === brandName.toLowerCase() && (!category || b.category === category),
  )
  return brand ? brand.models : []
}

/** Получить страну бренда по названию (без учёта регистра) */
export function getBrandCountry(brandName: string): CountryCode | undefined {
  const brand = ALL_BRANDS.find(
    (b) => b.name.toLowerCase() === brandName.toLowerCase(),
  )
  return brand ? brand.country : undefined
}

export const POPULAR_BRANDS = Array.from(new Map(_rawPopular.map(b=>[b.name,b])).values())
