-- Normalize the remaining short identifiers generated by the legacy
-- seed-categories script. The predicate is deliberately scoped to the
-- known demo account and only values shorter than a VIN, so user data is
-- never rewritten.

UPDATE "Vehicle"
SET "vin" = 'D' || UPPER(SUBSTR(REPLACE("id", '-', ''), 1, 16))
WHERE "vehicleType" IN ('CAR', 'MOTORCYCLE', 'TRUCK')
  AND LENGTH("vin") < 17
  AND "userId" IN (SELECT "id" FROM "User" WHERE "email" = 'demo@avtorynok.ru');

-- The same legacy seed referenced a non-existent placeholder CDN. Let the UI
-- show its compact no-photo state instead of producing broken image requests.
UPDATE "Vehicle"
SET "images" = NULL
WHERE "images" LIKE '%cdn.autmart.ru/placeholder/%';
